/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad_guia85.vistas;

import java.util.TreeSet;
import universidad_guia85.accesoadatos.AlumnoData;

/**
 *
 * @author Guillermo Rodriguez
 */
public class MenuPrincipal extends javax.swing.JFrame {
 public static TreeSet<AlumnoData> listaAlumnoData = new TreeSet<>();
 
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAlumno = new javax.swing.JMenu();
        MenuItemFormularioAlum = new javax.swing.JMenuItem();
        MenuMateria = new javax.swing.JMenu();
        MenuFormularioMateria = new javax.swing.JMenuItem();
        MenuAdministracion = new javax.swing.JMenu();
        MenuManejodeInscripcion = new javax.swing.JMenuItem();
        MenuManipulacionNotas = new javax.swing.JMenuItem();
        MenuConsultas = new javax.swing.JMenu();
        MenuAlumporMateria = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenu();

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        MenuAlumno.setText("Alumno");
        MenuAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAlumnoActionPerformed(evt);
            }
        });

        MenuItemFormularioAlum.setText("Formulario de Alumno");
        MenuItemFormularioAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemFormularioAlumActionPerformed(evt);
            }
        });
        MenuAlumno.add(MenuItemFormularioAlum);

        jMenuBar1.add(MenuAlumno);

        MenuMateria.setText("Materia");
        MenuMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMateriaActionPerformed(evt);
            }
        });

        MenuFormularioMateria.setText("Formulario de Materia");
        MenuFormularioMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFormularioMateriaActionPerformed(evt);
            }
        });
        MenuMateria.add(MenuFormularioMateria);

        jMenuBar1.add(MenuMateria);

        MenuAdministracion.setText("Administracion");
        MenuAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAdministracionActionPerformed(evt);
            }
        });

        MenuManejodeInscripcion.setText("Manejo de Inscripciones");
        MenuManejodeInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuManejodeInscripcionActionPerformed(evt);
            }
        });
        MenuAdministracion.add(MenuManejodeInscripcion);

        MenuManipulacionNotas.setText("Manipulacion de Notas");
        MenuManipulacionNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuManipulacionNotasActionPerformed(evt);
            }
        });
        MenuAdministracion.add(MenuManipulacionNotas);

        jMenuBar1.add(MenuAdministracion);

        MenuConsultas.setText("Consultas");
        MenuConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConsultasActionPerformed(evt);
            }
        });

        MenuAlumporMateria.setText("Alumnos por Materia");
        MenuAlumporMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAlumporMateriaActionPerformed(evt);
            }
        });
        MenuConsultas.add(MenuAlumporMateria);

        jMenuBar1.add(MenuConsultas);

        MenuSalir.setText("Salir");
        jMenuBar1.add(MenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemFormularioAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemFormularioAlumActionPerformed
     Escritorio.removeAll();
        Escritorio.repaint();
        AlumnosIF aif = new AlumnosIF();
        aif.setVisible(true);
        Escritorio.add(aif);
        Escritorio.moveToFront(aif);
    }//GEN-LAST:event_MenuItemFormularioAlumActionPerformed

    private void MenuAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAlumnoActionPerformed
      
    }//GEN-LAST:event_MenuAlumnoActionPerformed

    private void MenuMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuMateriaActionPerformed

    private void MenuFormularioMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFormularioMateriaActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        MateriasIF mif = new MateriasIF();
        mif.setVisible(true);
        Escritorio.add(mif);
        Escritorio.moveToFront(mif);
    }//GEN-LAST:event_MenuFormularioMateriaActionPerformed

    private void MenuAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAdministracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuAdministracionActionPerformed

    private void MenuManejodeInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuManejodeInscripcionActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        FormularioDeInscripcionIF fiif = new FormularioDeInscripcionIF();
        fiif.setVisible(true);
        Escritorio.add(fiif);
        Escritorio.moveToFront(fiif);
    }//GEN-LAST:event_MenuManejodeInscripcionActionPerformed

    private void MenuManipulacionNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuManipulacionNotasActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        CargaDeNotasIF cnif = new CargaDeNotasIF();
        cnif.setVisible(true);
        Escritorio.add(cnif);
        Escritorio.moveToFront(cnif);
    }//GEN-LAST:event_MenuManipulacionNotasActionPerformed

    private void MenuConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuConsultasActionPerformed

    private void MenuAlumporMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAlumporMateriaActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        ConsultaDeAlumnoPorMateriaIF camif = new ConsultaDeAlumnoPorMateriaIF ();
        camif.setVisible(true);
        Escritorio.add(camif);
        Escritorio.moveToFront(camif);
    }//GEN-LAST:event_MenuAlumporMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu MenuAdministracion;
    private javax.swing.JMenu MenuAlumno;
    private javax.swing.JMenuItem MenuAlumporMateria;
    private javax.swing.JMenu MenuConsultas;
    private javax.swing.JMenuItem MenuFormularioMateria;
    private javax.swing.JMenuItem MenuItemFormularioAlum;
    private javax.swing.JMenuItem MenuManejodeInscripcion;
    private javax.swing.JMenuItem MenuManipulacionNotas;
    private javax.swing.JMenu MenuMateria;
    private javax.swing.JMenu MenuSalir;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
